/**
 * 预设供应商数据（「添加供应商」弹窗一键填充用）
 *
 * 数据来源：cc-switch（github.com/farion1231/cc-switch，MIT License）
 * src/config/claudeProviderPresets.ts，已做如下整理：
 *   - 只保留可直接用 API Key 接入的 Anthropic 格式端点；
 *     OAuth 类（GitHub Copilot / Codex / xAI）、需格式转换类（gemini_native /
 *     openai_chat / openai_responses）、含模板变量类（AWS Bedrock / KAT-Coder）
 *     及无 baseURL 的官方预设不适用本应用，未收录；
 *   - 官网 / 获取 Key 链接已去除 cc-switch 的推广（aff/utm 等）参数；
 *   - baseUrl 即各供应商 ANTHROPIC_BASE_URL，接口格式均为 anthropic。
 */
import type { ProviderKind } from "../types";

export interface ProviderPreset {
  /** 建议供应商标识（字母/数字/-/_，用户可改） */
  id: string;
  /** 供应商名称 */
  name: string;
  /** 官网链接 */
  websiteUrl: string;
  /** 获取 API Key 的链接（缺省回退官网） */
  apiKeyUrl?: string;
  /** 接口格式（当前预设均为 Anthropic Messages 格式） */
  kind: ProviderKind;
  /** Base URL */
  baseUrl: string;
  /** 分类：cn_official=国内官方 / aggregator=聚合平台 / third_party=第三方 */
  category: "cn_official" | "aggregator" | "third_party";
}

/** 分类展示顺序与中文标签（下拉 optgroup 用） */
export const PRESET_CATEGORY_LABELS: Array<{
  key: ProviderPreset["category"];
  label: string;
}> = [
  { key: "cn_official", label: "国内官方" },
  { key: "aggregator", label: "聚合平台" },
  { key: "third_party", label: "第三方" },
];

export const PRESET_PROVIDERS: ProviderPreset[] = [
  // ===== 国内官方 =====
  {
    id: "kimi",
    name: "Kimi",
    websiteUrl: "https://platform.kimi.com",
    kind: "anthropic",
    baseUrl: "https://api.moonshot.cn/anthropic",
    category: "cn_official",
  },
  {
    id: "kimi-coding",
    name: "Kimi For Coding",
    websiteUrl: "https://www.kimi.com/code/",
    kind: "anthropic",
    baseUrl: "https://api.kimi.com/coding/",
    category: "cn_official",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    websiteUrl: "https://platform.deepseek.com",
    kind: "anthropic",
    baseUrl: "https://api.deepseek.com/anthropic",
    category: "cn_official",
  },
  {
    id: "zhipu-glm",
    name: "Zhipu GLM",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://www.bigmodel.cn/claude-code",
    kind: "anthropic",
    baseUrl: "https://open.bigmodel.cn/api/anthropic",
    category: "cn_official",
  },
  {
    id: "zhipu-glm-en",
    name: "Zhipu GLM en",
    websiteUrl: "https://z.ai",
    kind: "anthropic",
    baseUrl: "https://api.z.ai/api/anthropic",
    category: "cn_official",
  },
  {
    id: "volc-agent-plan",
    name: "火山 Agent Plan",
    websiteUrl: "https://www.volcengine.com/activity/agentplan",
    apiKeyUrl: "https://console.volcengine.com/ark",
    kind: "anthropic",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan",
    category: "cn_official",
  },
  {
    id: "volc-coding-plan",
    name: "火山 Coding Plan",
    websiteUrl: "https://www.volcengine.com/activity/codingplan",
    apiKeyUrl: "https://console.volcengine.com/ark",
    kind: "anthropic",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    category: "cn_official",
  },
  {
    id: "byteplus",
    name: "BytePlus",
    websiteUrl: "https://www.byteplus.com/en/product/modelark",
    kind: "anthropic",
    baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding",
    category: "cn_official",
  },
  {
    id: "doubao-seed",
    name: "DouBaoSeed",
    websiteUrl: "https://console.volcengine.com/ark",
    apiKeyUrl: "https://console.volcengine.com/ark",
    kind: "anthropic",
    baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
    category: "cn_official",
  },
  {
    id: "qianfan-coding",
    name: "Baidu Qianfan Coding Plan",
    websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
    apiKeyUrl:
      "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    kind: "anthropic",
    baseUrl: "https://qianfan.baidubce.com/anthropic/coding",
    category: "cn_official",
  },
  {
    id: "qianfan-token",
    name: "Baidu Qianfan Token Plan",
    websiteUrl: "https://cloud.baidu.com/product/codingplan.html",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/resource/token-plan",
    kind: "anthropic",
    baseUrl: "https://qianfan.baidubce.com/anthropic/tokenplan/personal",
    category: "cn_official",
  },
  {
    id: "bailian",
    name: "Bailian",
    websiteUrl: "https://bailian.console.aliyun.com",
    kind: "anthropic",
    baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
    category: "cn_official",
  },
  {
    id: "bailian-coding",
    name: "Bailian For Coding",
    websiteUrl: "https://bailian.console.aliyun.com",
    kind: "anthropic",
    baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
    category: "cn_official",
  },
  {
    id: "stepfun",
    name: "StepFun",
    websiteUrl: "https://platform.stepfun.com/step-plan",
    apiKeyUrl: "https://platform.stepfun.com/interface-key",
    kind: "anthropic",
    baseUrl: "https://api.stepfun.com/step_plan",
    category: "cn_official",
  },
  {
    id: "stepfun-en",
    name: "StepFun en",
    websiteUrl: "https://platform.stepfun.ai/step-plan",
    apiKeyUrl: "https://platform.stepfun.ai/interface-key",
    kind: "anthropic",
    baseUrl: "https://api.stepfun.ai/step_plan",
    category: "cn_official",
  },
  {
    id: "longcat",
    name: "Longcat",
    websiteUrl: "https://longcat.chat/platform",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
    kind: "anthropic",
    baseUrl: "https://api.longcat.chat/anthropic",
    category: "cn_official",
  },
  {
    id: "minimax",
    name: "MiniMax",
    websiteUrl: "https://platform.minimaxi.com",
    apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
    kind: "anthropic",
    baseUrl: "https://api.minimaxi.com/anthropic",
    category: "cn_official",
  },
  {
    id: "minimax-en",
    name: "MiniMax en",
    websiteUrl: "https://platform.minimax.io",
    apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
    kind: "anthropic",
    baseUrl: "https://api.minimax.io/anthropic",
    category: "cn_official",
  },
  {
    id: "bailing",
    name: "BaiLing",
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
    kind: "anthropic",
    baseUrl: "https://api.tbox.cn/api/anthropic",
    category: "cn_official",
  },
  {
    id: "xiaomi-mimo",
    name: "Xiaomi MiMo",
    websiteUrl: "https://platform.xiaomimimo.com",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/api-keys",
    kind: "anthropic",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    category: "cn_official",
  },
  {
    id: "xiaomi-mimo-token",
    name: "Xiaomi MiMo Token Plan (China)",
    websiteUrl: "https://platform.xiaomimimo.com/#/token-plan",
    apiKeyUrl: "https://platform.xiaomimimo.com/#/console/plan-manage",
    kind: "anthropic",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
    category: "cn_official",
  },
  // ===== 聚合平台 =====
  {
    id: "modelscope",
    name: "ModelScope",
    websiteUrl: "https://modelscope.cn",
    kind: "anthropic",
    baseUrl: "https://api-inference.modelscope.cn",
    category: "aggregator",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    websiteUrl: "https://siliconflow.cn",
    apiKeyUrl: "https://cloud.siliconflow.cn",
    kind: "anthropic",
    baseUrl: "https://api.siliconflow.cn",
    category: "aggregator",
  },
  {
    id: "siliconflow-en",
    name: "SiliconFlow en",
    websiteUrl: "https://siliconflow.com",
    apiKeyUrl: "https://cloud.siliconflow.cn",
    kind: "anthropic",
    baseUrl: "https://api.siliconflow.com",
    category: "aggregator",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    kind: "anthropic",
    baseUrl: "https://openrouter.ai/api",
    category: "aggregator",
  },
  {
    id: "therouter",
    name: "TheRouter",
    websiteUrl: "https://therouter.ai",
    apiKeyUrl: "https://dashboard.therouter.ai",
    kind: "anthropic",
    baseUrl: "https://api.therouter.ai",
    category: "aggregator",
  },
  {
    id: "novita",
    name: "Novita AI",
    websiteUrl: "https://novita.ai",
    kind: "anthropic",
    baseUrl: "https://api.novita.ai/anthropic",
    category: "aggregator",
  },
  {
    id: "ppio",
    name: "PPIO",
    websiteUrl: "https://ppio.com",
    apiKeyUrl: "https://ppio.com/settings/key-management",
    kind: "anthropic",
    baseUrl: "https://api.ppio.com/anthropic",
    category: "aggregator",
  },
  {
    id: "jiekou",
    name: "JieKou AI",
    websiteUrl: "https://jiekou.ai",
    apiKeyUrl: "https://jiekou.ai/settings/key-management",
    kind: "anthropic",
    baseUrl: "https://api.jiekou.ai/anthropic",
    category: "aggregator",
  },
  {
    id: "aihubmix",
    name: "AiHubMix",
    websiteUrl: "https://aihubmix.com",
    kind: "anthropic",
    baseUrl: "https://aihubmix.com",
    category: "aggregator",
  },
  {
    id: "cherryin",
    name: "CherryIN",
    websiteUrl: "https://open.cherryin.ai",
    apiKeyUrl: "https://open.cherryin.ai/console/token",
    kind: "anthropic",
    baseUrl: "https://open.cherryin.net",
    category: "aggregator",
  },
  {
    id: "pipellm",
    name: "PIPELLM",
    websiteUrl: "https://code.pipellm.ai",
    kind: "anthropic",
    baseUrl: "https://cc-api.pipellm.ai",
    category: "aggregator",
  },
  {
    id: "atlascloud",
    name: "AtlasCloud",
    websiteUrl: "https://www.atlascloud.ai",
    apiKeyUrl: "https://www.atlascloud.ai/console/coding-plan",
    kind: "anthropic",
    baseUrl: "https://api.atlascloud.ai",
    category: "aggregator",
  },
  {
    id: "compshare",
    name: "Compshare",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    kind: "anthropic",
    baseUrl: "https://api.modelverse.cn",
    category: "aggregator",
  },
  {
    id: "compshare-coding",
    name: "Compshare Coding Plan",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    kind: "anthropic",
    baseUrl: "https://cp.compshare.cn",
    category: "aggregator",
  },
  {
    id: "zetaapi",
    name: "ZetaAPI",
    websiteUrl: "https://zetaapi.ai",
    kind: "anthropic",
    baseUrl: "https://api.zetaapi.ai",
    category: "aggregator",
  },
  {
    id: "fennoai",
    name: "FennoAI",
    websiteUrl: "https://api.fenno.ai",
    kind: "anthropic",
    baseUrl: "https://api.fenno.ai",
    category: "aggregator",
  },
  {
    id: "runapi",
    name: "RunAPI",
    websiteUrl: "https://runapi.host",
    kind: "anthropic",
    baseUrl: "https://runapi.host",
    category: "aggregator",
  },
  {
    id: "shengsuanyun",
    name: "Shengsuanyun",
    websiteUrl: "https://www.shengsuanyun.com",
    kind: "anthropic",
    baseUrl: "https://router.shengsuanyun.com/api",
    category: "aggregator",
  },
  {
    id: "qiniu",
    name: "Qiniu",
    websiteUrl: "https://www.qiniu.com",
    kind: "anthropic",
    baseUrl: "https://api.qnaigc.com",
    category: "aggregator",
  },
  {
    id: "subrouter",
    name: "SubRouter",
    websiteUrl: "https://subrouter.ai",
    kind: "anthropic",
    baseUrl: "https://subrouter.ai",
    category: "aggregator",
  },
  {
    id: "claudeapi",
    name: "ClaudeAPI (APITo)",
    websiteUrl: "https://www.apito.ai",
    kind: "anthropic",
    baseUrl: "https://gw.apito.ai",
    category: "aggregator",
  },
  {
    id: "code0",
    name: "Code0",
    websiteUrl: "https://code0.ai",
    kind: "anthropic",
    baseUrl: "https://code0.ai",
    category: "aggregator",
  },
  {
    id: "teamorouter",
    name: "TeamoRouter",
    websiteUrl: "https://teamorouter.com",
    kind: "anthropic",
    baseUrl: "https://api.teamorouter.com",
    category: "aggregator",
  },
  {
    id: "a6api",
    name: "A6API",
    websiteUrl: "https://www.a6api.com",
    kind: "anthropic",
    baseUrl: "https://api.a6api.com",
    category: "aggregator",
  },
  {
    id: "ccsub",
    name: "CCSub",
    websiteUrl: "https://www.ccsub.net",
    kind: "anthropic",
    baseUrl: "https://www.ccsub.net",
    category: "aggregator",
  },
  {
    id: "dmxapi",
    name: "DMXAPI",
    websiteUrl: "https://www.dmxapi.cn",
    kind: "anthropic",
    baseUrl: "https://www.dmxapi.cn",
    category: "aggregator",
  },
  {
    id: "xycai",
    name: "XycAi",
    websiteUrl: "https://xycai.us",
    kind: "anthropic",
    baseUrl: "https://apicdn.xycai.us",
    category: "aggregator",
  },
  {
    id: "amux",
    name: "Amux",
    websiteUrl: "https://amux.ai",
    kind: "anthropic",
    baseUrl: "https://api.amux.ai",
    category: "aggregator",
  },
  // ===== 第三方 =====
  {
    id: "packycode",
    name: "PackyCode",
    websiteUrl: "https://www.packyapi.ai",
    kind: "anthropic",
    baseUrl: "https://www.packyapi.ai",
    category: "third_party",
  },
  {
    id: "apinebula",
    name: "APINebula",
    websiteUrl: "https://apinebula.ai",
    kind: "anthropic",
    baseUrl: "https://apinebula.ai",
    category: "third_party",
  },
  {
    id: "aicodemirror",
    name: "AICodeMirror",
    websiteUrl: "https://www.aicodemirror.ai",
    kind: "anthropic",
    baseUrl: "https://api.aicodemirror.ai/api/claudecode",
    category: "third_party",
  },
  {
    id: "patewayai",
    name: "PatewayAI",
    websiteUrl: "https://pateway.ai",
    kind: "anthropic",
    baseUrl: "https://api.pateway.ai",
    category: "third_party",
  },
  {
    id: "aigocode",
    name: "AIGoCode",
    websiteUrl: "https://aigocode.app",
    kind: "anthropic",
    baseUrl: "https://api.aigocode.app",
    category: "third_party",
  },
  {
    id: "aicoding",
    name: "AICoding",
    websiteUrl: "https://aicoding.inc",
    kind: "anthropic",
    baseUrl: "https://api.aicoding.inc",
    category: "third_party",
  },
  {
    id: "apikeyfun",
    name: "APIKEY.FUN",
    websiteUrl: "https://apikey.fun",
    kind: "anthropic",
    baseUrl: "https://api.apikey.fun",
    category: "third_party",
  },
  {
    id: "claudecn",
    name: "ClaudeCN",
    websiteUrl: "https://claudecn.top",
    kind: "anthropic",
    baseUrl: "https://claudecn.top",
    category: "third_party",
  },
  {
    id: "sssaicode",
    name: "SSSAiCode",
    websiteUrl: "https://sssaicodeapi.com",
    kind: "anthropic",
    baseUrl: "https://node-hk.sssaicodeapi.com/api",
    category: "third_party",
  },
  {
    id: "micu",
    name: "Micu",
    websiteUrl: "https://www.micuapi.ai",
    kind: "anthropic",
    baseUrl: "https://www.micuapi.ai",
    category: "third_party",
  },
  {
    id: "rightcode",
    name: "RightCode",
    websiteUrl: "https://www.rightapi.ai",
    kind: "anthropic",
    baseUrl: "https://www.rightapi.ai/claude",
    category: "third_party",
  },
  {
    id: "etok",
    name: "ETok.ai",
    websiteUrl: "https://etok.ai",
    kind: "anthropic",
    baseUrl: "https://api.etok.ai",
    category: "third_party",
  },
  {
    id: "cubence",
    name: "Cubence",
    websiteUrl: "https://cubence.com",
    kind: "anthropic",
    baseUrl: "https://api.cubence.com",
    category: "third_party",
  },
  {
    id: "crazyrouter",
    name: "CrazyRouter",
    websiteUrl: "https://www.crazyrouter.com",
    kind: "anthropic",
    baseUrl: "https://cn.crazyrouter.com",
    category: "third_party",
  },
  {
    id: "sudocode",
    name: "SudoCode.chat",
    websiteUrl: "https://sudocode.chat",
    kind: "anthropic",
    baseUrl: "https://api.sudocode.chat",
    category: "third_party",
  },
  {
    id: "sudocode-us",
    name: "SudoCode.us",
    websiteUrl: "https://sudocode.us",
    kind: "anthropic",
    baseUrl: "https://sudocode.us",
    category: "third_party",
  },
  {
    id: "relaxycode",
    name: "RelaxyCode",
    websiteUrl: "https://www.relaxycode.com",
    kind: "anthropic",
    baseUrl: "https://www.relaxycode.com",
    category: "third_party",
  },
  {
    id: "eflowcode",
    name: "E-FlowCode",
    websiteUrl: "https://e-flowcode.cc",
    kind: "anthropic",
    baseUrl: "https://e-flowcode.cc",
    category: "third_party",
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    websiteUrl: "https://opencode.ai/go",
    kind: "anthropic",
    baseUrl: "https://opencode.ai/zen/go",
    category: "third_party",
  },
];
